### ISSUE TITLE
Compatibility with other gapps

### ISSUE THREAD

**Issue by uzen** [raulx222/aroma-lp-gapps#2]
For compatibility with other packages can change the function call with "remove" in the "backup" in the update-script. At the same time do not forget to change the name in "backuptool.functions"

example https://github.com/uzen/slimlp_gapps/commit/13957273497956e695261f839d376b9b610216de

**Comment by raulx222** [comment]
the backuptool.fuctions isn't needed :D..you can execute directly the backup script...but only thing you have to do for this to work is to import the /tmp/backuptool.functions file only if it exists.. look here https://github.com/raulx222/aroma-lp-gapps/blob/master/extras/80-gapps.sh

And I can execute the backup script with "remove" from updater-script without the backuptool.functions :D
